### ISSUE TITLE
Add API support for the IBM Kubernetes service.

### ISSUE THREAD

**Issue by bigdatasourav** [IBM/platform-services-go-sdk#163]
**Is your feature request related to a problem? Please describe.**
Unable to get Kubernetes Cluster information for Pods and Containers such as HostIPC, HostNetwork, CPU and Memory limits for containers, service account details.  

**Describe the solution you'd like**
Want to have Clusters Pods and Containers level details - HostIPC, HostNetwork, CPU, and Memory limits for containers, service account, Container privileges.

**Describe alternatives you've considered**

**Additional context**

**Comment by padamstx** [comment]
This project contains the "platform services" category of IBM Cloud services.  Unfortunately, there doesn't yet seem to be an SDK that covers the Kubernetes service.  Please re-direct your request to the Kubernetes service.

**Comment by bigdatasourav** [comment]
@padamstx thanks for your response earlier. Just to confirm once, are you referring to redirect issues [here](https://github.com/kubernetes/client-go), also just like other services available in this repo, should we expect IBM will come up with the sdk support e.g. https://docs.aws.amazon.com/sdk-for-go/api/service/eks/ for provided for AWS?

**Comment by padamstx** [comment]
> @padamstx thanks for your response earlier. Just to confirm once, are you referring to redirect issues [here](https://github.com/kubernetes/client-go), also just like other services available in this repo, should we expect IBM will come up with the sdk support e.g. https://docs.aws.amazon.com/sdk-for-go/api/service/eks/ for provided for AWS?

I'm not familiar with the kubernetes "client-go" SDK project so I cannot say whether it would meet your needs or not.

Within IBM, we do have an overall goal of providing SDKs for all or most IBM Cloud services because we certainly recognize the value that SDKs bring to our customers in terms of improving the consumability of our various services.  
I unfortunately do not have any specific information about the IBM Kubernetes service. However, you could perhaps open a support case by first opening the [IBM Cloud Kubernetes Service API Reference page](https://cloud.ibm.com/apidocs/kubernetes), then click "Support" on the top menu bar, then click "Open a case".

**Comment by rajlearner17** [comment]
@padamstx thank you very much for this info, we will surely raise the issue, I work in the same team as @bigdatasourav, taking this privilege to respond. Thank you

**Comment by rajlearner17** [comment]
Raised this in IBM Community https://ibmcloud.ideas.ibm.com/ideas/IDEA-I-3403 and support case with IBM. Hope it gets attention. Thanks!!

**Comment by l2fprod** [comment]
@rajlearner17 did you look into the Containers SDK used by the IBM terraform provider? https://github.com/IBM-Cloud/container-services-go-sdk might help

**Comment by rajlearner17** [comment]
@l2fprod appreciate sending this note, not recollecting now, if we tried this inrush of testing many options. But for sure we will give it a try again and update in 2-3 days. Thank you
